sudo: required
services:
 - docker 

before_install:
 - docker build -t akshay008/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run akshay008/react-test npm test -- --coverage

after_success:
 - docker build -t akshay008/multi-client ./client
 - docker build -t akshay008/multi-nginx ./nginx
 - docker build -t akshay008/multi-server ./server
 - docker build -t akshay008/multi-worker ./worker

 #login to docker cli 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #take those images and push docker hub
 - docker push akshay008/multi-client
 - docker push akshay008/multi-nginx
 - docker push akshay008/multi-server
 - docker push akshay008/multi-worker

deploy:
 edge: true
 provider: elasticbeanstalk
 region: ap-south-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-ap-south-1-563535919868
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY 


